### PR TITLE
Update Facebook SDK to 9.0.1

### PR DESCRIPTION
**Pull request by mattleibow**
Reverting #198 as there was something off about the diff and several breaking changes that should not have happened.

### CODE REVIEW

**Comment by mattleibow** [comment]
# API diff: Facebook.CoreKit.dll

## Facebook.CoreKit.dll

### Namespace Facebook.CoreKit

#### Type Changed: Facebook.CoreKit.AccessToken

Removed properties:

```csharp
public string AppId { get; }
public bool IsDataAccessExpired { get; }
public bool IsExpired { get; }
public string UserId { get; }
```

Modified properties:

```diff
-public virtual Foundation.NSSet DeclinedPermissions { get; }
+public virtual Foundation.NSSet<Foundation.NSString> DeclinedPermissions { get; }
-public virtual Foundation.NSSet ExpiredPermissions { get; }
+public virtual Foundation.NSSet<Foundation.NSString> ExpiredPermissions { get; }
-public virtual Foundation.NSSet Permissions { get; }
+public virtual Foundation.NSSet<Foundation.NSString> Permissions { get; }
```

Removed methods:

```csharp
public virtual bool Equals (AccessToken token);
public static System.Threading.Tasks.Task<GraphRequestResult> RefreshCurrentAccessTokenAsync ();
```


#### Type Changed: Facebook.CoreKit.AccessTokenDidChangeEventArgs

Removed property:

```csharp
public bool DidExpireKey { get; }
```


#### Type Changed: Facebook.CoreKit.AccessTokensBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (AccessToken[] tokens, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (AccessToken[] arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (AccessToken[] tokens, Foundation.NSError error---arg1---)
+public virtual void Invoke (AccessToken[] arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.AppEventName

Modified fields:

```diff
-AdClick = 23
+AdClick = 22
-AdImpression = 22
+AdImpression = 21
-StartTrial = 19
+StartTrial = 18
-SubmitApplication = 20
+SubmitApplication = 19
-Subscribe = 21
+Subscribe = 20
```


#### Type Changed: Facebook.CoreKit.AppEventParameterProduct

Removed values:

```csharp
AppLinkiOSAppName = 7,
AppLinkiOSAppStoreId = 6,
AppLinkiOSUrl = 5,
AppLinkiPadAppName = 13,
AppLinkiPadAppStoreId = 12,
AppLinkiPadUrl = 11,
AppLinkiPhoneAppName = 10,
AppLinkiPhoneAppStoreId = 9,
AppLinkiPhoneUrl = 8,
```

Modified fields:

```diff
-AppLinkAndroidAppName = 16
+AppLinkAndroidAppName = 17
-AppLinkAndroidPackage = 15
+AppLinkAndroidPackage = 16
-AppLinkAndroidUrl = 14
+AppLinkAndroidUrl = 15
-AppLinkWindowsPhoneAppId = 18
+AppLinkWindowsPhoneAppId = 19
-AppLinkWindowsPhoneAppName = 19
+AppLinkWindowsPhoneAppName = 20
-AppLinkWindowsPhoneUrl = 17
+AppLinkWindowsPhoneUrl = 18
-CustomLabel0 = 0
+CustomLabel0 = 1
-CustomLabel1 = 1
+CustomLabel1 = 2
-CustomLabel2 = 2
+CustomLabel2 = 3
-CustomLabel3 = 3
+CustomLabel3 = 4
-CustomLabel4 = 4
+CustomLabel4 = 5
```


#### Type Changed: Facebook.CoreKit.AppEvents

Removed methods:

```csharp
public static void AugmentHybrid (WebKit.WKWebView webView);
public static string GetUserData ();
public static void LogEvent (AppEventName eventName);
protected static void LogEvent (Foundation.NSString eventName);
public static void LogEvent (AppEventName eventName, Foundation.NSDictionary parameters);
public static void LogEvent (AppEventName eventName, double valueToSum);
protected static void LogEvent (Foundation.NSString eventName, Foundation.NSDictionary parameters);
protected static void LogEvent (Foundation.NSString eventName, double valueToSum);
public static void LogEvent (AppEventName eventName, double valueToSum, Foundation.NSDictionary parameters);
protected static void LogEvent (Foundation.NSString eventName, double valueToSum, Foundation.NSDictionary parameters);
public static void LogEvent (AppEventName eventName, Foundation.NSNumber valueToSum, Foundation.NSDictionary parameters, AccessToken accessToken);
protected static void LogEvent (Foundation.NSString eventName, Foundation.NSNumber valueToSum, Foundation.NSDictionary parameters, AccessToken accessToken);
public static GraphRequest RequestForCustomAudienceThirdPartyId (AccessToken accessToken);
public static void SetPushNotificationsDeviceToken (string deviceTokenString);
public static System.Threading.Tasks.Task<GraphRequestResult> UpdateUserPropertiesAsync (Foundation.NSDictionary properties);
```


#### Type Changed: Facebook.CoreKit.AppLink

Removed method:

```csharp
public static AppLink Create (Foundation.NSUrl sourceUrl, AppLinkTarget[] targets, Foundation.NSUrl webUrl);
```


#### Type Changed: Facebook.CoreKit.AppLinkBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (AppLink appLink, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (AppLink arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (AppLink appLink, Foundation.NSError error---arg1---)
+public virtual void Invoke (AppLink arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.AppLinkNavigation

Modified properties:

```diff
-public IAppLinkResolving DefaultResolver { get; set; }
+public AppLinkResolving DefaultResolver { get; set; }
```

Removed methods:

```csharp
public static AppLinkNavigation Create (AppLink appLink, Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> extras, Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> appLinkData);
public static Foundation.NSDictionary<Foundation.NSString,Foundation.NSDictionary<Foundation.NSString,Foundation.NSString>> GetCallbackAppLinkData (string appName, string url);
public virtual AppLinkNavigationType GetNavigationType ();
public static AppLinkNavigationType GetNavigationType (AppLink link);
public static AppLinkNavigationType Navigate (AppLink link, out Foundation.NSError error);
public static void Navigate (Foundation.NSUrl destination, AppLinkNavigationBlockHandler handler);
public static void Navigate (Foundation.NSUrl destination, IAppLinkResolving resolver, AppLinkNavigationBlockHandler handler);
public static System.Threading.Tasks.Task<AppLinkNavigationType> NavigateAsync (Foundation.NSUrl destination);
public static System.Threading.Tasks.Task<AppLinkNavigationType> NavigateAsync (Foundation.NSUrl destination, IAppLinkResolving resolver);
public static void ResolveAppLink (Foundation.NSUrl destination, IAppLinkResolving resolver, AppLinkBlockHandler handler);
public static System.Threading.Tasks.Task<AppLink> ResolveAppLinkAsync (Foundation.NSUrl destination);
public static System.Threading.Tasks.Task<AppLink> ResolveAppLinkAsync (Foundation.NSUrl destination, IAppLinkResolving resolver);
```


#### Type Changed: Facebook.CoreKit.AppLinkNavigationBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (AppLinkNavigationType navType, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (AppLinkNavigationType arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (AppLinkNavigationType navType, Foundation.NSError error---arg1---)
+public virtual void Invoke (AppLinkNavigationType arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.AppLinkResolver

Removed property:

```csharp
public static AppLinkResolver Resolver { get; }
```

Removed methods:

```csharp
public virtual void GetAppLinks (Foundation.NSUrl[] urls, AppLinksBlockHandler handler);
public virtual System.Threading.Tasks.Task<Foundation.NSDictionary<Foundation.NSUrl,Facebook.CoreKit.AppLink>> GetAppLinksAsync (Foundation.NSUrl[] urls);
```


#### Type Changed: Facebook.CoreKit.AppLinkReturnToRefererController

Modified properties:

```diff
-public IAppLinkReturnToRefererControllerDelegate Delegate { get; set; }
+public AppLinkReturnToRefererControllerDelegate Delegate { get; set; }
```

Removed events:

```csharp
public event System.EventHandler<AppLinkReturnToRefererControllerNavigatedToAppLinkEventArgs> NavigatedToAppLink;
public event System.EventHandler<AppLinkReturnToRefererControllerWillNavigateToAppLinkEventArgs> WillNavigateToAppLink;
```

Removed methods:

```csharp
public virtual void CloseView (bool animated);
public virtual void DidTapInsideCloseButton (AppLinkReturnToRefererView view);
public virtual void DidTapInsideLink (AppLinkReturnToRefererView view, AppLink link);
public virtual void ShowView (AppLink refererAppLink);
public virtual void ShowView (Foundation.NSUrl url);
```


#### Type Changed: Facebook.CoreKit.AppLinkReturnToRefererView

Modified properties:

```diff
-public IAppLinkReturnToRefererViewDelegate Delegate { get; set; }
+public AppLinkReturnToRefererViewDelegate Delegate { get; set; }
```


#### Type Changed: Facebook.CoreKit.AppLinkReturnToRefererViewDelegate

Removed methods:

```csharp
public virtual void DidTapInsideCloseButton (AppLinkReturnToRefererView view);
public virtual void DidTapInsideLink (AppLinkReturnToRefererView view, AppLink link);
```


#### Type Changed: Facebook.CoreKit.AppLinkTarget

Removed method:

```csharp
public static AppLinkTarget Create (Foundation.NSUrl url, string appStoreId, string appName);
```


#### Type Changed: Facebook.CoreKit.AppLinkUtility

Removed methods:

```csharp
public static string AppInvitePromotionCode (Foundation.NSUrl url);
public static System.Threading.Tasks.Task<Foundation.NSUrl> FetchDeferredAppLinkAsync ();
```


#### Type Changed: Facebook.CoreKit.AppLinksBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (Foundation.NSDictionary<Foundation.NSUrl,Facebook.CoreKit.AppLink> appLinks, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (Foundation.NSDictionary<Foundation.NSUrl,Facebook.CoreKit.AppLink> arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (Foundation.NSDictionary<Foundation.NSUrl,Facebook.CoreKit.AppLink> appLinks, Foundation.NSError error---arg1---)
+public virtual void Invoke (Foundation.NSDictionary<Foundation.NSUrl,Facebook.CoreKit.AppLink> arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.ApplicationDelegate

Removed method:

```csharp
public static void InitializeSdk (Foundation.NSDictionary launchOptions);
```


#### Type Changed: Facebook.CoreKit.Button

Removed constructor:

```csharp
public Button (CoreGraphics.CGRect frame);
```


#### Type Changed: Facebook.CoreKit.CoreError

Removed values:

```csharp
BridgeApiInterruption = 13,
GraphRequestGraphApi = 8,
```


#### Type Changed: Facebook.CoreKit.ErrorBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (Foundation.NSError error, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (Foundation.NSError arg0, System.AsyncCallback callback, object object)
-public virtual void Invoke (Foundation.NSError error)
+public virtual void Invoke (Foundation.NSError arg0)
```


#### Type Changed: Facebook.CoreKit.ErrorRecoveryAttempting

Removed method:

```csharp
public virtual void AttemptRecovery (Foundation.NSError error, uint recoveryOptionIndex, Foundation.NSObject aDelegate, ObjCRuntime.Selector didRecoverSelector, IntPtr contextInfo);
```


#### Type Changed: Facebook.CoreKit.GraphErrorRecoveryProcessor

Modified properties:

```diff
-public IGraphErrorRecoveryProcessorDelegate Delegate { get; }
+public GraphErrorRecoveryProcessorDelegate Delegate { get; }
```

Removed method:

```csharp
public virtual bool ProcessError (Foundation.NSError error, GraphRequest request, IGraphErrorRecoveryProcessorDelegate aDelegate);
```


#### Type Changed: Facebook.CoreKit.GraphErrorRecoveryProcessorDelegate

Removed methods:

```csharp
public virtual void DidAttemptRecovery (GraphErrorRecoveryProcessor processor, bool didRecover, Foundation.NSError error);
public virtual bool WillProcessError (GraphErrorRecoveryProcessor processor, Foundation.NSError error);
```


#### Type Changed: Facebook.CoreKit.GraphErrorRecoveryProcessorDelegate_Extensions

Removed method:

```csharp
public static bool WillProcessError (this IGraphErrorRecoveryProcessorDelegate This, GraphErrorRecoveryProcessor processor, Foundation.NSError error);
```


#### Type Changed: Facebook.CoreKit.GraphRequest

Removed property:

```csharp
public HttpMethod HttpMethod { get; }
```

Modified properties:

```diff
-public virtual Foundation.NSDictionary Parameters { get; set; }
+public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> Parameters { get; +++set;+++ }
```


#### Type Changed: Facebook.CoreKit.GraphRequestBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (GraphRequestConnection connection, Foundation.NSObject result---arg1---, Foundation.NSError error---arg2---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (GraphRequestConnection arg0, Foundation.NSObject +++result+++arg1, Foundation.NSError +++error+++arg2, System.AsyncCallback callback, object object)
-public virtual void Invoke (GraphRequestConnection connection, Foundation.NSObject result---arg1---, Foundation.NSError error---arg2---)
+public virtual void Invoke (GraphRequestConnection arg0, Foundation.NSObject +++result+++arg1, Foundation.NSError +++error+++arg2)
```


#### Type Changed: Facebook.CoreKit.GraphRequestConnection

Removed property:

```csharp
public static Foundation.NSString NonJsonResponsePropertyKey { get; }
```

Modified properties:

```diff
-public IGraphRequestConnectionDelegate Delegate { get; set; }
+public GraphRequestConnectionDelegate Delegate { get; set; }
```

Removed events:

```csharp
public event System.EventHandler<GraphRequestConnectionBodyDataSentEventArgs> BodyDataSent;
public event System.EventHandler<GraphRequestConnectionFailedEventArgs> Failed;
public event System.EventHandler LoadingFinished;
public event System.EventHandler WillBeginLoading;
```

Removed methods:

```csharp
public virtual System.Threading.Tasks.Task<GraphRequestResult> AddRequestAsync (GraphRequest request);
public virtual System.Threading.Tasks.Task<GraphRequestResult> AddRequestAsync (GraphRequest request, Foundation.NSDictionary batchParameters);
public virtual System.Threading.Tasks.Task<GraphRequestResult> AddRequestAsync (GraphRequest request, string name);
public virtual void OverrideGraphApiVersion (string version);
```


#### Type Changed: Facebook.CoreKit.GraphRequestConnectionDelegate

Removed methods:

```csharp
public virtual void DidFail (GraphRequestConnection connection, Foundation.NSError error);
public virtual void DidFinishLoading (GraphRequestConnection connection);
public virtual void DidSendBodyData (GraphRequestConnection connection, nint bytesWritten, nint totalBytesWritten, nint totalBytesExpectedToWrite);
public virtual void WillBeginLoading (GraphRequestConnection connection);
```


#### Type Changed: Facebook.CoreKit.GraphRequestConnectionDelegate_Extensions

Removed methods:

```csharp
public static void DidFail (this IGraphRequestConnectionDelegate This, GraphRequestConnection connection, Foundation.NSError error);
public static void DidFinishLoading (this IGraphRequestConnectionDelegate This, GraphRequestConnection connection);
public static void DidSendBodyData (this IGraphRequestConnectionDelegate This, GraphRequestConnection connection, nint bytesWritten, nint totalBytesWritten, nint totalBytesExpectedToWrite);
public static void WillBeginLoading (this IGraphRequestConnectionDelegate This, GraphRequestConnection connection);
```


#### Type Changed: Facebook.CoreKit.IAppLinkReturnToRefererViewDelegate

Removed methods:

```csharp
public virtual void DidTapInsideCloseButton (AppLinkReturnToRefererView view);
public virtual void DidTapInsideLink (AppLinkReturnToRefererView view, AppLink link);
```


#### Type Changed: Facebook.CoreKit.IErrorRecoveryAttempting

Removed method:

```csharp
public virtual void AttemptRecovery (Foundation.NSError error, uint recoveryOptionIndex, Foundation.NSObject aDelegate, ObjCRuntime.Selector didRecoverSelector, IntPtr contextInfo);
```


#### Type Changed: Facebook.CoreKit.IGraphErrorRecoveryProcessorDelegate

Removed method:

```csharp
public virtual void DidAttemptRecovery (GraphErrorRecoveryProcessor processor, bool didRecover, Foundation.NSError error);
```


#### Type Changed: Facebook.CoreKit.Profile

Removed properties:

```csharp
public static Foundation.NSString NewProfileKey { get; }
public static Foundation.NSString OldProfileKey { get; }
```

Removed methods:

```csharp
public virtual bool Equals (Profile profile);
public virtual Foundation.NSUrl ImageUrl (ProfilePictureMode mode, CoreGraphics.CGSize size);
public static void LoadCurrentProfile (ProfileBlockHandler completion);
public static System.Threading.Tasks.Task<Profile> LoadCurrentProfileAsync ();
```


#### Type Changed: Facebook.CoreKit.ProfileBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (Profile profile, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (Profile arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (Profile profile, Foundation.NSError error---arg1---)
+public virtual void Invoke (Profile arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.Settings

Removed properties:

```csharp
public static bool AutoInitEnabled { get; set; }
public static string DefaultGraphApiVersion { get; }
public static string GraphApiVersion { get; set; }
public static nfloat JpegCompressionQuality { get; set; }
```

Modified properties:

```diff
-public LoggingBehavior[] LoggingBehaviors { get; set; }
+public Foundation.NSSet<Foundation.NSString> LoggingBehaviors { get; set; }
```

Removed methods:

```csharp
public static void DisableLoggingBehavior (LoggingBehavior loggingBehavior);
public static void EnableLoggingBehavior (LoggingBehavior loggingBehavior);
```


#### Type Changed: Facebook.CoreKit.TestUsersManager

Removed methods:

```csharp
public virtual void AddTestAccount (Foundation.NSSet permissions, AccessTokensBlockHandler handler);
public virtual System.Threading.Tasks.Task<AccessToken[]> AddTestAccountAsync (Foundation.NSSet permissions);
public virtual void MakeFriends (AccessToken first, AccessToken second, ErrorBlockHandler handler);
public virtual System.Threading.Tasks.Task MakeFriendsAsync (AccessToken first, AccessToken second);
public virtual System.Threading.Tasks.Task RemoveTestAccountAsync (string userId);
public virtual void RequestTestAccount (Foundation.NSSet[] arraysOfPermissions, bool createIfNotFound, AccessTokensBlockHandler handler);
public virtual System.Threading.Tasks.Task<AccessToken[]> RequestTestAccountAsync (Foundation.NSSet[] arraysOfPermissions, bool createIfNotFound);
public static TestUsersManager SharedInstance (string appId, string appSecret);
```


#### Type Changed: Facebook.CoreKit.UrlBlockHandler

Modified methods:

```diff
-public virtual System.IAsyncResult BeginInvoke (Foundation.NSUrl url, Foundation.NSError error---arg1---, System.AsyncCallback callback, object object)
+public virtual System.IAsyncResult BeginInvoke (Foundation.NSUrl arg0, Foundation.NSError +++error+++arg1, System.AsyncCallback callback, object object)
-public virtual void Invoke (Foundation.NSUrl url, Foundation.NSError error---arg1---)
+public virtual void Invoke (Foundation.NSUrl arg0, Foundation.NSError +++error+++arg1)
```


#### Type Changed: Facebook.CoreKit.Utility

Removed methods:

```csharp
public static Foundation.NSDictionary CreateDictionary (string queryString);

[Obsolete ("Use CreateDictionary method instead. This will be removed in future versions.")]
public static Foundation.NSDictionary DictionaryWithQueryString (string queryString);

[Obsolete ("Use CreateQueryString method instead. This will be removed in future versions.")]
public static string QueryStringWithDictionary (Foundation.NSDictionary dictionary, out Foundation.NSError errorRef);
```


#### Removed Type Facebook.CoreKit.AppLinkReturnToRefererControllerNavigatedToAppLinkEventArgs
#### Removed Type Facebook.CoreKit.AppLinkReturnToRefererControllerWillNavigateToAppLinkEventArgs
#### Removed Type Facebook.CoreKit.AutoAppLinkPresentationStyle
#### Removed Type Facebook.CoreKit.GraphRequestConnectionBodyDataSentEventArgs
#### Removed Type Facebook.CoreKit.GraphRequestConnectionFailedEventArgs
#### Removed Type Facebook.CoreKit.GraphRequestResult
#### Removed Type Facebook.CoreKit.MutableCopying

**Comment by mattleibow** [comment]
# API diff: Facebook.ShareKit.dll

## Facebook.ShareKit.dll

### Namespace Facebook.ShareKit

#### Type Changed: Facebook.ShareKit.AppInviteContent

Removed property:

```csharp
public Foundation.NSUrl PreviewImageUrl { get; set; }
```

Removed method:

```csharp
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.CameraEffectArguments

Removed methods:

```csharp
public virtual string[] GetArray (string key);
public virtual string GetString (string key);
```

Modified methods:

```diff
-public virtual void SetString (string aString, string key)
+public virtual void SetString (string string, string key)
```


#### Type Changed: Facebook.ShareKit.CameraEffectTextures

Removed method:

```csharp
public virtual UIKit.UIImage GetImage (string key);
```


#### Type Changed: Facebook.ShareKit.GameRequestContent

Removed method:

```csharp
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.GameRequestDialog

Removed constructor:

```csharp
public GameRequestDialog ();
```

Modified properties:

```diff
-public IGameRequestDialogDelegate Delegate { get; set; }
+public GameRequestDialogDelegate Delegate { get; set; }
```

Removed events:

```csharp
public event System.EventHandler Cancelled;
public event System.EventHandler<GameRequestDialogCompletedEventArgs> Completed;
public event System.EventHandler<GameRequestDialogFailedEventArgs> Failed;
```

Removed methods:

```csharp
public static GameRequestDialog Create (GameRequestContent content, IGameRequestDialogDelegate aDelegate);
public static GameRequestDialog Show (GameRequestContent content, IGameRequestDialogDelegate aDelegate);
public virtual bool Validate (out Foundation.NSError error);
```


#### Type Changed: Facebook.ShareKit.GameRequestDialogDelegate

Removed methods:

```csharp
public virtual void DidCancel (GameRequestDialog gameRequestDialog);
public virtual void DidComplete (GameRequestDialog gameRequestDialog, Foundation.NSDictionary results);
public virtual void DidFail (GameRequestDialog gameRequestDialog, Foundation.NSError error);
```


#### Type Changed: Facebook.ShareKit.Hashtag

Modified properties:

```diff
 public virtual bool Valid { get; ---set;--- }
```

Removed method:

```csharp
public static Hashtag Create (string hashtag);
```


#### Type Changed: Facebook.ShareKit.IGameRequestDialogDelegate

Removed methods:

```csharp
public virtual void DidCancel (GameRequestDialog gameRequestDialog);
public virtual void DidComplete (GameRequestDialog gameRequestDialog, Foundation.NSDictionary results);
public virtual void DidFail (GameRequestDialog gameRequestDialog, Foundation.NSError error);
```


#### Type Changed: Facebook.ShareKit.ISharingButton

Removed methods:

```csharp
public virtual ISharingContent GetShareContent ();
public virtual void SetShareContent (ISharingContent shareContent);
```


#### Type Changed: Facebook.ShareKit.ISharingContent

Removed property:

```csharp
public string ShareUuid { get; }
```

Removed methods:

```csharp
public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> AddParameters (Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> existingParameters, ShareBridgeOptions bridgeOptions);
public virtual Foundation.NSUrl GetContentUrl ();
public virtual string[] GetPeopleIds ();
public virtual string GetPlaceId ();
public virtual string GetRef ();
public virtual void SetContentUrl (Foundation.NSUrl url);
public virtual void SetPeopleIds (string[] peolpleId);
public virtual void SetPlaceId (string placeId);
public virtual void SetRef (string aRef);
```


#### Type Changed: Facebook.ShareKit.ISharingDelegate

Removed methods:

```csharp
public virtual void DidCancel (ISharing sharer);
public virtual void DidComplete (ISharing sharer, Foundation.NSDictionary results);
public virtual void DidFail (ISharing sharer, Foundation.NSError error);
```


#### Type Changed: Facebook.ShareKit.ISharingDialog

Removed method:

```csharp
public virtual bool CanShow ();
```


#### Type Changed: Facebook.ShareKit.ISharingScheme

Removed method:

```csharp
public virtual string GetScheme (ShareDialogMode mode);
```


#### Type Changed: Facebook.ShareKit.ISharingValidation

Removed method:

```csharp
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.Liking

Modified constructors:

```diff
-public Liking ()
+protected Liking ()
```

Removed methods:

```csharp
public virtual string GetObjectId ();
public virtual LikeObjectType GetObjectType ();
public virtual void SetObjectId (string id);
public virtual void SetObjectType (LikeObjectType type);
```


#### Type Changed: Facebook.ShareKit.MessageDialog

Removed methods:

```csharp
public virtual bool CanShow ();
public static MessageDialog Create (ISharingContent content, ISharingDelegate aDelegate);
public virtual ISharingDelegate GetDelegate ();
public virtual ISharingContent GetShareContent ();
public virtual bool GetShouldFailOnDataError ();
public virtual void SetDelegate (ISharingDelegate aDelegate);
public virtual void SetShareContent (ISharingContent shareContent);
public virtual void SetShouldFailOnDataError (bool shouldFail);
public static MessageDialog Show (ISharingContent content, ISharingDelegate aDelegate);
```


#### Type Changed: Facebook.ShareKit.SendButton

Removed constructor:

```csharp
public SendButton (CoreGraphics.CGRect frame);
```

Removed methods:

```csharp
public virtual ISharingContent GetShareContent ();
public virtual void SetShareContent (ISharingContent shareContent);
```


#### Type Changed: Facebook.ShareKit.ShareButton

Removed constructor:

```csharp
public ShareButton (CoreGraphics.CGRect frame);
```

Removed methods:

```csharp
public virtual ISharingContent GetShareContent ();
public virtual void SetShareContent (ISharingContent shareContent);
```


#### Type Changed: Facebook.ShareKit.ShareCameraEffectContent

Removed property:

```csharp
public string ShareUuid { get; }
```

Removed methods:

```csharp
public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> AddParameters (Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> existingParameters, ShareBridgeOptions bridgeOptions);
public virtual Foundation.NSUrl GetContentUrl ();
public virtual string[] GetPeopleIds ();
public virtual string GetPlaceId ();
public virtual string GetRef ();
public virtual string GetScheme (ShareDialogMode mode);
public virtual void SetContentUrl (Foundation.NSUrl url);
public virtual void SetPeopleIds (string[] peolpleId);
public virtual void SetPlaceId (string placeId);
public virtual void SetRef (string aRef);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.ShareDialog

Removed methods:

```csharp
public virtual bool CanShow ();
public static ShareDialog Create (UIKit.UIViewController viewController, ISharingContent content, ISharingDelegate aDelegate);
public virtual ISharingDelegate GetDelegate ();
public virtual ISharingContent GetShareContent ();
public virtual bool GetShouldFailOnDataError ();
public virtual void SetDelegate (ISharingDelegate aDelegate);
public virtual void SetShareContent (ISharingContent shareContent);
public virtual void SetShouldFailOnDataError (bool shouldFail);
public static ShareDialog Show (UIKit.UIViewController viewController, ISharingContent content, ISharingDelegate aDelegate);
```


#### Type Changed: Facebook.ShareKit.ShareLinkContent

Removed property:

```csharp
public string ShareUuid { get; }
```

Removed methods:

```csharp
public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> AddParameters (Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> existingParameters, ShareBridgeOptions bridgeOptions);
public virtual Foundation.NSUrl GetContentUrl ();
public virtual string[] GetPeopleIds ();
public virtual string GetPlaceId ();
public virtual string GetRef ();
public virtual void SetContentUrl (Foundation.NSUrl url);
public virtual void SetPeopleIds (string[] peolpleId);
public virtual void SetPlaceId (string placeId);
public virtual void SetRef (string aRef);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.ShareMediaContent

Modified properties:

```diff
-public virtual IShareMedia[] Media { get; set; }
+public virtual ShareMedia[] Media { get; set; }
```


#### Type Changed: Facebook.ShareKit.SharePhoto

Removed methods:

```csharp
public static SharePhoto From (Foundation.NSUrl imageURL, bool userGenerated);
public static SharePhoto From (Photos.PHAsset photoAsset, bool userGenerated);
public static SharePhoto From (UIKit.UIImage image, bool userGenerated);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.SharePhotoContent

Removed property:

```csharp
public string ShareUuid { get; }
```

Removed methods:

```csharp
public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> AddParameters (Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> existingParameters, ShareBridgeOptions bridgeOptions);
public virtual Foundation.NSUrl GetContentUrl ();
public virtual string[] GetPeopleIds ();
public virtual string GetPlaceId ();
public virtual string GetRef ();
public virtual void SetContentUrl (Foundation.NSUrl url);
public virtual void SetPeopleIds (string[] peolpleId);
public virtual void SetPlaceId (string placeId);
public virtual void SetRef (string aRef);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.ShareVideo

Removed methods:

```csharp
public static ShareVideo From (Foundation.NSData data);
public static ShareVideo From (Foundation.NSUrl videoURL);
public static ShareVideo From (Photos.PHAsset videoAsset);
public static ShareVideo From (Foundation.NSData data, SharePhoto previewPhoto);
public static ShareVideo From (Foundation.NSUrl videoURL, SharePhoto previewPhoto);
public static ShareVideo From (Photos.PHAsset videoAsset, SharePhoto previewPhoto);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.ShareVideoContent

Removed property:

```csharp
public string ShareUuid { get; }
```

Removed methods:

```csharp
public virtual Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> AddParameters (Foundation.NSDictionary<Foundation.NSString,Foundation.NSObject> existingParameters, ShareBridgeOptions bridgeOptions);
public virtual Foundation.NSUrl GetContentUrl ();
public virtual string[] GetPeopleIds ();
public virtual string GetPlaceId ();
public virtual string GetRef ();
public virtual void SetContentUrl (Foundation.NSUrl url);
public virtual void SetPeopleIds (string[] peolpleId);
public virtual void SetPlaceId (string placeId);
public virtual void SetRef (string aRef);
public virtual bool Validate (ShareBridgeOptions bridgeOptions, out Foundation.NSError errorRef);
```


#### Type Changed: Facebook.ShareKit.SharingDelegate

Removed methods:

```csharp
public virtual void DidCancel (ISharing sharer);
public virtual void DidComplete (ISharing sharer, Foundation.NSDictionary results);
public virtual void DidFail (ISharing sharer, Foundation.NSError error);
```


#### Removed Type Facebook.ShareKit.GameRequestDialogCompletedEventArgs
#### Removed Type Facebook.ShareKit.GameRequestDialogFailedEventArgs
#### Removed Type Facebook.ShareKit.Liking_Extensions
#### Removed Type Facebook.ShareKit.Sharing_Extensions

**Comment by mattleibow** [comment]
The above 3 comments have the breaking changes diff ^^^

**Comment by thisisthekap** [comment]
@mattleibow Just curious: Did you use some specific tooling to create the API diffs?

**Comment by dalexsoto** [comment]
Replaced by https://github.com/xamarin/FacebookComponents/pull/204

**Pull request closed without merging**
