### PR TITLE
fixed android dependencies for sdk 7.1.0 (fixes issue #194)

### LINKED ISSUE #194: Xamarin.Facebook.Android 7.1.0 dependencies are broken
## Referenced in solution although not referenced by maven package 7.1.0

* facebook-livestreaming 4.36.0
* facebook-loginkit 4.36.0
* facebook-marketing 7.0.1
* account-kit-sdk 5.4.0
* audience-network-sdk 5.10.1
* notifications 1.0.2

## Referenced by maven package 7.1.0, but not in solution

* facebook-gamingservices 7.1.0

## Library dependency not referenced in facebook-core (but referenced by maven package)

* com.android.installreferrer (nuget Xamarin.Android.Binding.InstallReferrer)

### PR DESCRIPTION
**Pull request by thisisthekap**
fixes #194

### CODE REVIEW

**Comment by thisisthekap** [comment]
@SotoiGhost @Redth Seems that I somehow broke some checks. Unfortunately, I am not able to access the logs. May you grant me access or send me the log files?

**Comment by thisisthekap** [comment]
Converted to draft, because https://github.com/adjust/xamarin_sdk/issues/32 is blocking this fix.

It is quite likely, that users using the Adjust SDK are using the Facebook SDK alongside.

**Comment by johnclarete** [comment]
Hi @thisisthekap is there any further update on this one?

**Comment by thisisthekap** [comment]
@johnclarete I am waiting for the PR to be reviewed. So unfortunately no update from my side.

**Comment by tentom** [comment]
@mattleibow you closed one of the issues to update the SDK, could you take a look at this PR and #199  and/or point someone in the direction of these pull requests?  Not sure why this PR fails(cant see the azure logs) but I assume @thisisthekap had it compiling at some point. 

When native WebView authentication is removed on October 5, 2021 alternatives to the webView login will not work on apps targeting android 11 and running SDK version lower than 8.2 ( current version in this NuGet seems to be 7.1.0) and latest released by Facebook is 11.   


> We’ve been monitoring an increase in phishing attempts on Android embedded browsers, also known as WebViews. Because of this, we will no longer support this method of Facebook Login and your users will not be able to log in using Android embedded browsers beginning October 5, 2021. Until then, we will continue to prevent access to Facebook Login on embedded browsers for certain users we deem high-risk in an effort to prevent malicious activity.
> To avoid a disrupted user experience, please use the following checklist:
> Ensure that you have upgraded to version 8.2.0 (or later) of the Facebook SDK for Android. If your app is built to target Android 11 (API level 30) and your users are on Android 11, alternative non-webview login mechanisms provided by the SDK will not work unless you upgrade to or past 8.2.0....


Facebook is currently nagging about using version 7 of their SDK and that users must upgrade. 

> As part of our release of v9.0 SDKs, we are requiring developers to upgrade to our newest version. This upgrade will give developers new security features, enhanced resilience, and increased performance.
> Your current SDK is deprecated and will no longer be supported by Facebook. We will continue to allow API calls from your SDK for a transition period of two years. Starting January 19, 2023 we will fail all calls from deprecated SDKs. We encourage you to upgrade to v9.0 as soon as possible to avoid disruption to your application and to access all the benefits of our newest SDK."

**Pull request closed without merging**
